[#1] feature 회원 채팅 메세지 도메인 모델을 구현한다
woowa-chat/backend pull request #2
Opened 2023-04-24 13:37 UTC by shin-mallang

## 구현한거
- 회원 [Member] 도메인 엔티티 구현
- 채팅 [Chat] 도메인 엔티티 구현
- 메세지 [Message] 도메인 엔티티 구현
- Repository 구현

<br/>

## Todo
도메인 별로 필요한 기능 추가해야 합

<br/>

## Issue
close #1

2023-04-24 23:39 UTC, greeng00se requested changes
고생했어 코멘트 확인해줘~

2023-04-24 23:39 UTC, greeng00se commented on src/main/java/chat/woowa/woowachat/chat/Messages.java
> +    @JoinColumn(name = "chat_id")  // 연관관계의 주인을 chat 으로 지정
주석 없어도 될듯!

2023-04-24 23:39 UTC, greeng00se commented on src/main/java/chat/woowa/woowachat/chat/Role.java
> +    ASSISTANT("assistant"),
roleName의 용도가 어떻게 돼? GptModel은 따로 필드가 없는데 이건 따로 필드가 있어가지고 궁금해서

2023-04-24 23:39 UTC, greeng00se commented on src/main/java/chat/woowa/woowachat/chat/SettingMessage.java
> +    ;
혹시 이렇게 먼저 세팅하고 한국어로 질문하면 한국어로 답변이 잘와?

2023-04-24 23:39 UTC, greeng00se commented on src/test/java/chat/woowa/woowachat/WoowachatApplicationTests.java
> +}
사용하지 않으니 제거해도 될듯?

2023-04-24 23:39 UTC, greeng00se commented on src/test/java/chat/woowa/woowachat/chat/ChatRepositoryTest.java
> +class ChatRepositoryTest {
우리 중요도 순서로 애너테이션을 클래스 가까이 붙이도록 컨벤션을 정할까?

2023-04-24 23:55 UTC, shin-mallang commented on src/main/java/chat/woowa/woowachat/chat/Messages.java
> +    @JoinColumn(name = "chat_id")  // 연관관계의 주인을 chat 으로 지정
아하 오키~!

2023-04-24 23:57 UTC, shin-mallang commented on src/main/java/chat/woowa/woowachat/chat/Role.java
> +    ASSISTANT("assistant"),
헉 미안 GptModel에 이름을 추가하는 식으로 수정할게
Gpt api 요청할 때 chat의 role을 입력해줘야 하는데 USER.name().toLowerCase()보다는 미리 등록해두고 쓰는게 좋을 것 같아서 위처럼 작성했어!

2023-04-24 23:59 UTC, shin-mallang commented on src/main/java/chat/woowa/woowachat/chat/SettingMessage.java
> +    ;
그때그때 다른 것 같은데, 테스트결과 대체로 한국어, 가끔 영어로 답변이 왔어. 
그냥 한국어로 답을 원하면 한국어로 답 해주라 추가로 요청하지 않을까 해서..?
그냥 기본적으로 한국어로 답하도록 설정할까?

2023-04-25 00:00 UTC, shin-mallang commented on src/test/java/chat/woowa/woowachat/WoowachatApplicationTests.java
> +}
저거 그냥 앱 실행 전체적으로 잘되는지 테스트할 수 있어서 남겨두는 편인데 그냥 지워??

2023-04-25 00:02 UTC, shin-mallang commented on src/test/java/chat/woowa/woowachat/chat/ChatRepositoryTest.java
> +class ChatRepositoryTest {
위같은 경우
Supress
DisnameGen
Disname
jpaTest

순서인가?

2023-04-25 00:05 UTC, greeng00se commented on src/main/java/chat/woowa/woowachat/chat/SettingMessage.java
> +    ;
일단 한국어로 설정하는 것도 괜찮을듯! 가끔 영어로 답변 올 것 같아서

2023-04-25 00:05 UTC, greeng00se commented on src/test/java/chat/woowa/woowachat/chat/ChatRepositoryTest.java
> +class ChatRepositoryTest {
굳

2023-04-25 00:06 UTC, greeng00se commented on src/test/java/chat/woowa/woowachat/WoowachatApplicationTests.java
> +}
다른 테스트가 더 추가된다면 충분히 잘 돌아가는지 검증이 될 것 같아서?

2023-04-25 00:08 UTC, shin-mallang commented on src/main/java/chat/woowa/woowachat/chat/SettingMessage.java
> +    ;
오키오키 ~!~!

2023-04-25 00:11 UTC, shin-mallang commented on src/test/java/chat/woowa/woowachat/WoowachatApplicationTests.java
> +}
오키 반영할겡~!

2023-04-25 00:34 UTC, greeng00se approved these changes
LGTM 👍

2023-04-25 00:34 UTC, merged